# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_file_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1225, 754)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Launcher.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.plainTextEdit.setMouseTracking(False)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setOverwriteMode(False)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_find = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_find.sizePolicy().hasHeightForWidth())
        self.pushButton_find.setSizePolicy(sizePolicy)
        self.pushButton_find.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_find.setMaximumSize(QtCore.QSize(110, 16777215))
        self.pushButton_find.setObjectName("pushButton_find")
        self.gridLayout.addWidget(self.pushButton_find, 2, 13, 1, 1)
        self.label_dec_cnt = QtWidgets.QLabel(self.centralwidget)
        self.label_dec_cnt.setText("")
        self.label_dec_cnt.setObjectName("label_dec_cnt")
        self.gridLayout.addWidget(self.label_dec_cnt, 3, 4, 1, 1)
        self.pushButton_cmd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_cmd.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_cmd.setObjectName("pushButton_cmd")
        self.gridLayout.addWidget(self.pushButton_cmd, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 11, 1, 1)
        self.pushButton_plot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_plot.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.gridLayout.addWidget(self.pushButton_plot, 1, 2, 1, 1)
        self.pushButton_filter = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_filter.sizePolicy().hasHeightForWidth())
        self.pushButton_filter.setSizePolicy(sizePolicy)
        self.pushButton_filter.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_filter.setMaximumSize(QtCore.QSize(110, 16777215))
        self.pushButton_filter.setFlat(False)
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.gridLayout.addWidget(self.pushButton_filter, 1, 13, 1, 1, QtCore.Qt.AlignHCenter)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_2.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_2.setSizePolicy(sizePolicy)
        self.dateTimeEdit_2.setMinimumSize(QtCore.QSize(130, 0))
        self.dateTimeEdit_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.dateTimeEdit_2.setWrapping(False)
        self.dateTimeEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 1, 12, 1, 1)
        self.pushButton_man_dec = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_man_dec.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_man_dec.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_man_dec.setObjectName("pushButton_man_dec")
        self.gridLayout.addWidget(self.pushButton_man_dec, 1, 3, 1, 1)
        self.pushButton_source = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_source.sizePolicy().hasHeightForWidth())
        self.pushButton_source.setSizePolicy(sizePolicy)
        self.pushButton_source.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_source.setMaximumSize(QtCore.QSize(88, 16777215))
        self.pushButton_source.setObjectName("pushButton_source")
        self.gridLayout.addWidget(self.pushButton_source, 1, 1, 1, 1)
        self.dateTimeEdit_1 = QtWidgets.QDateTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_1.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_1.setSizePolicy(sizePolicy)
        self.dateTimeEdit_1.setMinimumSize(QtCore.QSize(130, 0))
        self.dateTimeEdit_1.setMaximumSize(QtCore.QSize(130, 16777215))
        self.dateTimeEdit_1.setWrapping(False)
        self.dateTimeEdit_1.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateTimeEdit_1.setObjectName("dateTimeEdit_1")
        self.gridLayout.addWidget(self.dateTimeEdit_1, 1, 10, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 14, 1, 1)
        self.lineEdit_find = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_find.sizePolicy().hasHeightForWidth())
        self.lineEdit_find.setSizePolicy(sizePolicy)
        self.lineEdit_find.setMaximumSize(QtCore.QSize(133, 16777215))
        self.lineEdit_find.setObjectName("lineEdit_find")
        self.gridLayout.addWidget(self.lineEdit_find, 2, 12, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(120, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_cancel_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel_search.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton_cancel_search.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_cancel_search.setStyleSheet("")
        self.pushButton_cancel_search.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_cancel_search.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/imageres_98.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cancel_search.setIcon(icon1)
        self.pushButton_cancel_search.setObjectName("pushButton_cancel_search")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel_search)
        self.lineEdit_new_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_new_search.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_new_search.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_new_search.setPlaceholderText("")
        self.lineEdit_new_search.setObjectName("lineEdit_new_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_new_search, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_find_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_find_up.setMinimumSize(QtCore.QSize(18, 11))
        self.pushButton_find_up.setMaximumSize(QtCore.QSize(18, 11))
        self.pushButton_find_up.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_find_up.setIcon(icon2)
        self.pushButton_find_up.setIconSize(QtCore.QSize(18, 10))
        self.pushButton_find_up.setObjectName("pushButton_find_up")
        self.verticalLayout_2.addWidget(self.pushButton_find_up, 0, QtCore.Qt.AlignTop)
        self.pushButton_find_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_find_down.setMinimumSize(QtCore.QSize(18, 11))
        self.pushButton_find_down.setMaximumSize(QtCore.QSize(18, 11))
        self.pushButton_find_down.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_find_down.setIcon(icon3)
        self.pushButton_find_down.setIconSize(QtCore.QSize(18, 10))
        self.pushButton_find_down.setObjectName("pushButton_find_down")
        self.verticalLayout_2.addWidget(self.pushButton_find_down)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.pushButton_new_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new_search.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_new_search.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_new_search.setObjectName("pushButton_new_search")
        self.horizontalLayout_2.addWidget(self.pushButton_new_search, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 6, 1, 1)
        self.label_search = QtWidgets.QLabel(self.centralwidget)
        self.label_search.setText("")
        self.label_search.setObjectName("label_search")
        self.gridLayout.addWidget(self.label_search, 2, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionkjids = QtWidgets.QAction(MainWindow)
        self.actionkjids.setObjectName("actionkjids")
        self.action13 = QtWidgets.QAction(MainWindow)
        self.action13.setObjectName("action13")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LogAnalysis"))
        self.pushButton_find.setText(_translate("MainWindow", "Фильтр по словам"))
        self.pushButton_cmd.setText(_translate("MainWindow", "Обработать отчет"))
        self.label.setText(_translate("MainWindow", "—"))
        self.pushButton_plot.setText(_translate("MainWindow", "Построить графики"))
        self.pushButton_filter.setText(_translate("MainWindow", "Фильтр по времени"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy HH:mm:ss"))
        self.pushButton_man_dec.setText(_translate("MainWindow", "Обработать вручную"))
        self.pushButton_source.setText(_translate("MainWindow", "Исходный файл"))
        self.dateTimeEdit_1.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy HH:mm:ss"))
        self.lineEdit_find.setPlaceholderText(_translate("MainWindow", "слово1; слово2"))
        self.pushButton_new_search.setText(_translate("MainWindow", "Поиск"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить как..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionkjids.setText(_translate("MainWindow", "12"))
        self.action13.setText(_translate("MainWindow", "13"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть файл"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
import resources_rc
